# Generated by Django 4.1.1 on 2022-09-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='auth_mail',
            new_name='author_mail',
        ),
        migrations.RenameField(
            model_name='authors',
            old_name='auth_name',
            new_name='author_name',
        ),
    ]
