# Generated by Django 4.1.1 on 2022-09-14 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_rename_auth_mail_authors_author_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year_pub',
        ),
    ]
